#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# Build ONE consolidated schema file for a fresh install: database/schema.sql
#
# Structure only — every row of data (mock/sample/production) is stripped. It
# merges:
#   1) the full table structure from the phpMyAdmin production dump (CREATE TABLE
#      + the ALTER TABLE keys/indexes/constraints), with all INSERT data removed
#   2) newer module tables that aren't in that dump yet (the create_*.sql files,
#      which are already schema-only, e.g. the Quotation Builder tables)
#
# Import database/schema.sql into a brand-new (empty) database to set up all
# tables with no data. Re-run this script after changing the dump or adding a
# create_*.sql migration.
#
# Usage:  bash database/build-schema.sh
# ─────────────────────────────────────────────────────────────────────────────
set -Eeuo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="$DIR/schema.sql"
DUMP="$(ls "$DIR"/u952547820_ecosudar*.sql 2>/dev/null | head -1 || true)"

# Target DB name from the rebrand config (used to rewrite the dump's old DB name).
BRAND_CFG="$DIR/../rebrand/brand.config.json"
NEW_DB=""
if [ -f "$BRAND_CFG" ] && command -v node >/dev/null 2>&1; then
  NEW_DB="$(node -e 'try{const c=require(process.argv[1]);process.stdout.write(String((c.database&&c.database.name)||""))}catch{}' "$BRAND_CFG" || true)"
fi
# Old DB name as embedded in the dump (from its "-- Database: \`X\`" header line).
OLD_DB=""
[ -n "$DUMP" ] && OLD_DB="$(grep -oE -- '-- Database: `[^`]+`' "$DUMP" | head -1 | sed -E 's/.*`([^`]+)`.*/\1/' || true)"
export OLD_DB NEW_DB

# View names in the dump — their stand-in tables + view definitions are dropped
# (the app doesn't use them, and they otherwise drag in DEFINER/DELIMITER issues).
VIEW_NAMES=""
[ -n "$DUMP" ] && VIEW_NAMES="$(grep -oE 'VIEW `[^`]+`' "$DUMP" | sed -E 's/VIEW `([^`]+)`/\1/' | sort -u | tr '\n' '|' | sed 's/|$//')"

# Bootstrap admin login captured during rebrand (rebrand/brand.config.json → "admin").
# Only the bcrypt hash is stored/seeded — never a plaintext password. This is the
# single data row the schema carries (a usable login, not demo data).
adm() { [ -f "$BRAND_CFG" ] && command -v node >/dev/null 2>&1 \
  && node -e 'try{const c=require(process.argv[1]);process.stdout.write(String((c.admin&&c.admin[process.argv[2]])||""))}catch{}' "$BRAND_CFG" "$1" || true; }
ADMIN_NAME="$(adm name)";  ADMIN_EMAIL="$(adm email)"; ADMIN_PHONE="$(adm phone)"
ADMIN_ROLE="$(adm staffRole)"; ADMIN_HASH="$(adm passwordHash)"
[ -z "$ADMIN_ROLE" ] && ADMIN_ROLE="owner"
sqlq() { printf '%s' "${1//\'/\'\'}"; }   # escape single quotes for SQL string literals

# Brand color from the rebrand config — seeded into the settings table so the new
# company's theme (app + sidebar + ID card) applies automatically, no manual step.
PRIMARY_COLOR=""
if [ -f "$BRAND_CFG" ] && command -v node >/dev/null 2>&1; then
  PRIMARY_COLOR="$(node -e 'try{const c=require(process.argv[1]);process.stdout.write(String(c.primaryColor||""))}catch{}' "$BRAND_CFG" || true)"
fi

{
  echo "-- ============================================================================"
  echo "-- Consolidated schema — all tables + ONE bootstrap admin login (no demo data)."
  echo "-- Generated by database/build-schema.sh. Do not edit by hand."
  echo "-- Import into an EMPTY database (e.g. via phpMyAdmin → Import)."
  echo "-- ============================================================================"
  echo "SET SQL_MODE='NO_AUTO_VALUE_ON_ZERO';"
  echo "SET FOREIGN_KEY_CHECKS=0;"
  echo "SET NAMES utf8mb4;"
  if [ -n "$NEW_DB" ]; then
    echo "-- Target database. It must already exist (create it in hPanel → MySQL first)."
    echo "-- This line removes the need to pre-select a database when importing."
    echo "USE \`$NEW_DB\`;"
  else
    echo "-- NOTE: no DB name configured — select your database in phpMyAdmin before importing."
  fi
  echo

  # 1) Structure from the production dump, made portable + data-free:
  #    - drop every multi-line "INSERT INTO … ;" block (no data)
  #    - drop the DELIMITER $$ … DELIMITER ; block (stored procedures/triggers —
  #      unused by the app and the source of "DECLARE/END unrecognized" errors)
  #    - drop views and their phpMyAdmin stand-in tables (also unused)
  #    - drop LOCK/UNLOCK TABLES and any CREATE DATABASE/USE (DB-name-neutral)
  #    - strip any leftover DEFINER clause and rewrite the old DB name to $NEW_DB
  #    Keep CREATE TABLE + ALTER TABLE (keys/indexes/constraints) + DROP TABLE + SET.
  if [ -n "$DUMP" ] && [ -f "$DUMP" ]; then
    echo "-- ── Core schema: base tables only (no data, no procedures/views) ───────────"
    # Normalise line endings first: phpMyAdmin dumps are often CRLF, and a trailing
    # \r makes the awk end-of-statement test (/;[ \t]*$/) never match — which would
    # make an INSERT skip swallow the rest of the file. tr -d '\r' avoids that.
    tr -d '\r' < "$DUMP" | awk -v views="$VIEW_NAMES" '
      BEGIN { n=split(views, a, "|"); for (i=1;i<=n;i++) if (a[i]!="") isview[a[i]]=1 }
      # stored-routine block: DELIMITER $$ … DELIMITER ;
      /^DELIMITER[ \t]+\$\$/ { dl=1; next }
      dl { if ($0 ~ /^DELIMITER[ \t]*;/) dl=0; next }
      # row data
      /^INSERT INTO/ { skip=1 }
      skip { if ($0 ~ /;[ \t]*$/) skip=0; next }
      /^LOCK TABLES/ || /^UNLOCK TABLES/ || /^CREATE DATABASE/ || /^USE / { next }
      # view-section comments
      /^-- Stand-in structure for view/ { next }
      /^-- Structure for view/ { next }
      # continuation of a skipped view / stand-in statement
      vskip { if ($0 ~ /;[ \t]*$/) vskip=0; next }
      # real view definition (single or multi line)
      (/^CREATE/ && / VIEW `/) { if ($0 ~ /;[ \t]*$/) next; vskip=1; next }
      # stand-in CREATE TABLE whose name is actually a view
      /^CREATE TABLE `/ {
        nm=$0; sub(/^CREATE TABLE `/,"",nm); sub(/`.*/,"",nm)
        if (nm in isview) { if ($0 ~ /;[ \t]*$/) next; vskip=1; next }
      }
      # DROP TABLE for a view name
      /^DROP TABLE IF EXISTS `/ {
        dn=$0; sub(/^DROP TABLE IF EXISTS `/,"",dn); sub(/`.*/,"",dn)
        if (dn in isview) next
      }
      { print }
    ' | perl -pe '
      s/DEFINER=`[^`]+`\@`[^`]+`\s*//g;     # remove any leftover DEFINER reference
      if ($ENV{OLD_DB} ne "" && $ENV{NEW_DB} ne "") { s/\Q$ENV{OLD_DB}\E/$ENV{NEW_DB}/g; }
    '
    echo
  fi

  # 2) Newer module tables not present in the dump (schema-only create_*.sql).
  #    These use CREATE TABLE IF NOT EXISTS, so they are safe even if a future
  #    dump already contains them.
  for f in "$DIR"/create_*.sql; do
    [ -f "$f" ] || continue
    if grep -qi "INSERT INTO" "$f"; then
      echo "-- (skipped $(basename "$f") — contains INSERT/data)"
      continue
    fi
    echo "-- ── $(basename "$f") ──────────────────────────────────────────────────"
    cat "$f"
    echo
  done

  # 3) Seed the single bootstrap admin login (no other data). INSERT IGNORE so a
  #    re-import won't fail on the UNIQUE email.
  if [ -n "$ADMIN_EMAIL" ] && [ -n "$ADMIN_HASH" ]; then
    echo "-- ── Bootstrap admin login (created during rebrand; the ONLY user row) ──────"
    echo "INSERT IGNORE INTO users (name, email, phone, password_hash, user_type, staff_role, approval_status, is_active)"
    echo "VALUES ('$(sqlq "${ADMIN_NAME:-Administrator}")', '$(sqlq "$ADMIN_EMAIL")', '$(sqlq "$ADMIN_PHONE")', '$(sqlq "$ADMIN_HASH")', 'admin', '$(sqlq "$ADMIN_ROLE")', 'approved', 1);"
    echo
  fi

  # Brand color seed → company_primary_color in settings (theme follows it on load).
  if [ -n "$PRIMARY_COLOR" ]; then
    echo "-- ── Brand color (from rebrand config → app/sidebar/ID-card theme) ──────────"
    echo "INSERT IGNORE INTO settings (setting_key, setting_value) VALUES ('company_primary_color', '$(sqlq "$PRIMARY_COLOR")');"
    echo
  fi

  echo "SET FOREIGN_KEY_CHECKS=1;"
  echo "COMMIT;"
} > "$OUT"

tables=$(grep -c "^CREATE TABLE" "$OUT" || true)
data_inserts=$(grep -c "^INSERT INTO " "$OUT" || true)   # plain data inserts (must be 0)
admin_seed=$(grep -c "^INSERT IGNORE INTO users" "$OUT" || true)
echo "Wrote $OUT"
echo "  CREATE TABLE statements: $tables"
echo "  Data INSERT statements:  $data_inserts   (must be 0 — no mock data)"
echo "  Admin seed (login row):  $admin_seed"
[ "$data_inserts" = "0" ] || { echo "ERROR: mock data leaked into schema.sql" >&2; exit 1; }
